services:
  - type: web
    name: arbitrage-scanner
    runtime: python
    env: python
    region: frankfurt
    plan: free
    branch: main
    startCommand: python main.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.7
